'use strict';
(function(){
const ACCOUNT='openscite_user_v1',PROFILES='openscite_profiles_v1';
const keys=[STORE.library,STORE.notes,STORE.highlights,'openscite_bookmarks_v25','openscite_positions_v25','openscite_tags_v25','openscite_chat_v1','openscite_history_v25'];
let current=loadJSON(ACCOUNT,{id:'guest',name:'訪客'}),token='',expires=0,busy=false;
const snapshot=()=>Object.fromEntries(keys.map(k=>[k,localStorage.getItem(k)]));
function persist(){const all=loadJSON(PROFILES,{});all[current.id]=snapshot();localStorage.setItem(PROFILES,JSON.stringify(all));}
function switchUser(user){if(state.aiBusy||state.reader.understandingBusy)throw Error('請先完成或取消目前分析');persist();const saved=loadJSON(PROFILES,{})[user.id]||{},before=snapshot(),previous=localStorage.getItem(ACCOUNT);try{for(const key of keys){if(saved[key]===undefined||saved[key]===null)localStorage.removeItem(key);else localStorage.setItem(key,saved[key]);}localStorage.setItem(ACCOUNT,JSON.stringify(user));}catch(e){for(const key of keys){if(before[key]===null)localStorage.removeItem(key);else localStorage.setItem(key,before[key]);}if(previous===null)localStorage.removeItem(ACCOUNT);else localStorage.setItem(ACCOUNT,previous);throw Error('儲存空間不足，已保留原本帳號資料');}current=user;token='';location.reload();}
const button=document.createElement('button');button.id='userAccount';button.className='btn';button.textContent=current.name||'訪客';$('settingsBtn').before(button);
const modal=document.createElement('dialog');modal.id='userAccountDialog';modal.className='model-dialog';modal.innerHTML='<div class="dialog-header"><h2>我的工作區</h2><button class="btn" id="closeUserAccount">關閉</button></div><p id="userAccountName"></p><p>論文庫、搜尋紀錄、對話、筆記與閱讀位置會自動保存在這台裝置。不同帳號的紀錄分開保存。</p><button class="btn primary" id="googleSignIn">使用 Google 登入</button><button class="btn" id="guestSignIn">使用訪客</button><p id="googleSetupStatus"></p><hr><h3>雲端紀錄</h3><p>登入 Google 後，可手動將紀錄備份到自己的 Google 雲端硬碟，或合併其他裝置的紀錄。PDF 原檔仍保存在本機，請另行備份。</p><button class="btn" id="cloudSave">備份至 Google</button><button class="btn" id="cloudRestore">從 Google 合併</button><p id="accountStatus" role="status"></p>';
document.body.append(modal);const el=id=>modal.querySelector('#'+id),cfg=window.PaperLumeAccountConfig||{},native=window.paperlumeDesktop?.googleLogin?window.paperlumeDesktop:null;let nativeConfigured=false;
function render(){el('userAccountName').textContent='目前：'+current.name;const configured=native?nativeConfigured:!!cfg.googleClientId&&!window.paperlumeDesktop;el('googleSignIn').disabled=!configured;el('googleSetupStatus').textContent=configured?'首次登入會請求基本帳號資訊及本應用程式的雲端備份權限。':window.paperlumeDesktop?'Google 登入尚待應用程式管理者設定，目前可使用訪客並保存紀錄。':'Google 登入尚待網站管理者設定，目前可使用訪客並保存紀錄。';for(const id of ['cloudSave','cloudRestore'])el(id).disabled=!configured||current.id==='guest'||busy;el('guestSignIn').disabled=current.id==='guest'||busy;}
button.onclick=()=>{render();modal.showModal();};el('closeUserAccount').onclick=()=>modal.close();
el('guestSignIn').onclick=async()=>{try{await native?.googleLogout();switchUser({id:'guest',name:'訪客'});}catch(e){el('accountStatus').textContent=e.message;}};
async function authorize(){if(native){await native.googleLogin();return;}if(token&&expires>Date.now()+60000)return;if(!window.google?.accounts?.oauth2)await new Promise((resolve,reject)=>{const script=document.createElement('script');script.src='https://accounts.google.com/gsi/client';script.onload=resolve;script.onerror=()=>reject(Error('Google 登入元件載入失敗'));document.head.append(script);});await new Promise((resolve,reject)=>{const client=google.accounts.oauth2.initTokenClient({client_id:cfg.googleClientId,scope:'openid email profile https://www.googleapis.com/auth/drive.appdata',callback:r=>{if(r.error||!r.access_token)return reject(Error('Google 授權未完成'));token=r.access_token;expires=Date.now()+Number(r.expires_in||3600)*1000;resolve();},error_callback:()=>reject(Error('登入視窗已關閉或無法開啟，請重試'))});client.requestAccessToken({prompt:''});});}
async function api(url,options={}){if(native)return native.googleRequest({url,...options});if(!token||expires<=Date.now())throw Error('Google 授權已到期，請重新登入');const response=await fetch(url,{...options,headers:{...options.headers,Authorization:'Bearer '+token},signal:AbortSignal.timeout(30000),redirect:'error'});if(!response.ok){if(response.status===401){token='';expires=0;}throw Error('Google 操作未完成（'+response.status+'）');}return response.status===204?null:response.json();}
async function identity(){const user=await api('https://www.googleapis.com/oauth2/v3/userinfo');if(typeof user.sub!=='string'||!user.sub)throw Error('無法確認 Google 帳號');return {id:'google:'+user.sub,name:user.name||user.email||'Google 使用者'};}
el('googleSignIn').onclick=()=>run(async()=>{await authorize();const user=await identity();if(current.id!==user.id)switchUser(user);else el('accountStatus').textContent='Google 授權已完成，可以備份或合併紀錄。';});
async function run(fn){if(busy)return;busy=true;render();el('googleSignIn').disabled=true;el('accountStatus').textContent='處理中…';try{await fn();}catch(e){el('accountStatus').textContent=e.message;}finally{busy=false;render();}}
async function authorizedAccount(){await authorize();const user=await identity();if(user.id!==current.id){token='';throw Error('選擇的 Google 帳號不同，請先切換工作區帳號');}}
async function remote(){const list=await api('https://www.googleapis.com/drive/v3/files?spaces=appDataFolder&q='+encodeURIComponent("name='openscite-workspace.json' and trashed=false")+'&fields=files(id,modifiedTime)&orderBy=modifiedTime%20desc&pageSize=10');if((list.files||[]).length>1)throw Error('發現多份雲端紀錄，請先匯出本機備份並整理雲端版本');return list.files?.[0]?.id;}
el('cloudSave').onclick=()=>run(async()=>{await authorizedAccount();const id=await remote();const data=JSON.stringify({format:'openscite-account',version:1,owner:current.id,savedAt:new Date().toISOString(),data:snapshot()});if(id){if(!confirm('以這台裝置的紀錄更新雲端備份？其他裝置尚未合併的修改不會保留。'))return;await api('https://www.googleapis.com/upload/drive/v3/files/'+encodeURIComponent(id)+'?uploadType=media',{method:'PATCH',headers:{'Content-Type':'application/json'},body:data});}else{const boundary='paperlume_'+crypto.randomUUID(),body='--'+boundary+'\r\nContent-Type: application/json; charset=UTF-8\r\n\r\n'+JSON.stringify({name:'openscite-workspace.json',parents:['appDataFolder']})+'\r\n--'+boundary+'\r\nContent-Type: application/json\r\n\r\n'+data+'\r\n--'+boundary+'--';await api('https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart',{method:'POST',headers:{'Content-Type':'multipart/related; boundary='+boundary},body});}el('accountStatus').textContent='紀錄已備份至 Google。';});
el('cloudRestore').onclick=()=>run(async()=>{await authorizedAccount();const id=await remote();if(!id)throw Error('此帳號還沒有雲端備份');const value=await api('https://www.googleapis.com/drive/v3/files/'+encodeURIComponent(id)+'?alt=media');if(value.format!=='openscite-account'||value.version!==1||value.owner!==current.id||!value.data||JSON.stringify(value).length>20000000)throw Error('雲端資料格式不正確');const decoded=Object.fromEntries(keys.filter(k=>value.data[k]!=null).map(k=>[k,JSON.parse(value.data[k])]));validateBackup({format:'openscite-workspace',version:1,data:decoded});if(decoded.openscite_history_v25!==undefined&&(!Array.isArray(decoded.openscite_history_v25)||!decoded.openscite_history_v25.every(x=>typeof x==='string')))throw Error('搜尋紀錄格式不正確');const staged={};for(const k of keys){const raw=value.data[k];if(raw===null||raw===undefined)continue;if(typeof raw!=='string')throw Error('紀錄格式不正確');const remote=JSON.parse(raw),local=loadJSON(k,Array.isArray(remote)?[]:{});if(!remote||typeof remote!=='object')throw Error('紀錄格式不正確');if(Array.isArray(remote)){if(!Array.isArray(local))throw Error('紀錄格式不正確');const identity=x=>typeof x==='string'?x:x.key||x.id||JSON.stringify(x);staged[k]=JSON.stringify([...new Map([...remote,...local].map(x=>[identity(x),x])).values()]);}else{if(Array.isArray(local))throw Error('紀錄格式不正確');staged[k]=JSON.stringify({...remote,...local});}}if(!confirm('合併雲端紀錄？相同項目會保留這台裝置的版本。'))return;const before=snapshot();try{for(const [k,v]of Object.entries(staged))localStorage.setItem(k,v);}catch(e){for(const [k,v]of Object.entries(before)){if(v===null)localStorage.removeItem(k);else localStorage.setItem(k,v);}throw Error('儲存空間不足，已復原');}location.reload();});
native?.googleStatus().then(s=>{nativeConfigured=s.configured;render();}).catch(()=>{});
modal.addEventListener('close',()=>native?.googleCancel().catch(()=>{}));
window.addEventListener('pagehide',()=>{try{persist();}catch{}});render();window.UserAccount={current:()=>({...current}),snapshot};
})();
