'use strict';
// OpenScite 25: workflow tools. No credentials are included in workspace exports.
const PREFS='openscite_workspace_v25', prefs=loadJSON(PREFS,{theme:'dark',density:'comfortable'});
function insertTools(selector,html,where='beforeend'){document.querySelector(selector).insertAdjacentHTML(where,html);}
insertTools('.nav-actions','<button id="themeToggle" class="btn ghost" aria-label="切換明暗主題">◐</button><button id="cancelAi" class="btn small hidden">取消 AI</button><button id="helpToggle" class="btn ghost" aria-label="鍵盤快捷鍵">?</button>');
insertTools('.search-card',`<div class="workflow-row"><div id="searchHistory" class="history-chips" aria-label="最近搜尋"></div><button id="densityToggle" class="btn small ghost">精簡列表</button><button id="exportSearch" class="btn small">匯出 BibTeX</button></div>`);
insertTools('#view-search',`<section id="compareTray" class="compare-tray hidden" aria-label="比較選取的論文"><span id="compareCount"></span><button id="compareOpen" class="btn small primary">比較論文</button><button id="compareClear" class="btn small">清除</button></section>`);
insertTools('.pdf-panel',`<div class="reader-commandbar"><div class="find-input"><label for="pdfFind" class="sr-only">搜尋文件全文</label><input id="pdfFind" class="control" placeholder="搜尋全文…  ⌘ / Ctrl F"><span id="findCount" role="status"></span></div><button id="findPrev" class="icon-btn" aria-label="上一筆命中">↑</button><button id="findNext" class="icon-btn" aria-label="下一筆命中">↓</button><button id="bookmarkPage" class="btn small" title="加入目前頁面書籤">☆ 書籤</button><button id="focusReader" class="btn small">專注閱讀</button><button id="downloadPdf" class="btn small" aria-label="下載原始 PDF">↓ PDF</button></div><div id="readerProgress" class="reader-progress" role="status">開啟 PDF 後即可全文搜尋</div>`,'afterbegin');
insertTools('.reader-left .panel-body',`<label class="stack-label">高亮顏色<select id="highlightColor" class="control"><option value="yellow">黃色 · 重點</option><option value="green">綠色 · 方法</option><option value="blue">藍色 · 數據</option><option value="pink">粉色 · 疑問</option></select></label><div class="document-navigation"><h4>文件導覽</h4><div class="document-nav-tabs"><button class="btn small" data-doc-nav="outline">目錄</button><button class="btn small" data-doc-nav="bookmarks">書籤</button><button class="btn small" data-doc-nav="matches">搜尋</button></div><div id="documentNav" class="document-nav"><p class="muted">尚未載入文件</p></div></div>`);
insertTools('#view-library .section-head',`<div class="row-actions"><button id="backupWorkspace" class="btn">匯出備份</button><button id="restoreWorkspace" class="btn">匯入備份</button><input id="backupFile" type="file" accept="application/json,.json" class="hidden"></div>`);
insertTools('#libraryList',`<div class="library-toolbar"><input id="libraryQuery" class="control" aria-label="搜尋論文庫" placeholder="搜尋標題、作者、標籤…"><select id="libraryOrder" class="control" aria-label="論文庫排序"><option value="added">最近收藏</option><option value="title">標題 A–Z</option><option value="year">年份新到舊</option></select><span id="libraryCount"></span></div>`,'beforebegin');
insertTools('body',`<dialog id="workspaceDialog"><div class="dialog-header"><h2 id="dialogTitle"></h2><button id="dialogClose" class="icon-btn" aria-label="關閉">×</button></div><div id="dialogContent"></div></dialog>`);
$('cancelAi').onclick=()=>state.aiController?.abort();
const dialog=$('workspaceDialog');$('dialogClose').onclick=()=>dialog.close();dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close();});
function showDialog(title,html){$('dialogTitle').textContent=title;$('dialogContent').innerHTML=html;dialog.showModal();}
function applyPrefs(){document.documentElement.dataset.theme=prefs.theme;document.body.classList.toggle('dense',prefs.density==='compact');$('densityToggle').textContent=prefs.density==='compact'?'舒適列表':'精簡列表';}
applyPrefs();$('themeToggle').onclick=()=>{prefs.theme=prefs.theme==='dark'?'light':'dark';saveJSON(PREFS,prefs);applyPrefs();};$('densityToggle').onclick=()=>{prefs.density=prefs.density==='compact'?'comfortable':'compact';saveJSON(PREFS,prefs);applyPrefs();};
$('helpToggle').onclick=()=>showDialog('鍵盤快捷鍵',`<div class="shortcut-list"><p><kbd>/</kbd> 搜尋論文</p><p><kbd>Ctrl / ⌘ K</kbd> 搜尋論文</p><p><kbd>Ctrl / ⌘ F</kbd> 閱讀器內搜尋全文</p><p><kbd>← / →</kbd> PDF 上一頁 / 下一頁</p><p><kbd>Esc</kbd> 離開專注閱讀 / 關閉視窗</p></div><p>PDF、筆記和閱讀位置在這台瀏覽器保存。備份包含論文資料、筆記、標註及書籤，不含 PDF 原檔與 API 金鑰。</p>`);
document.addEventListener('keydown',e=>{const edit=e.target.matches('input,textarea,select,[contenteditable="true"]');if(e.key==='Escape'){document.body.classList.remove('reader-focus');$('focusReader').textContent='專注閱讀';$('aiModal').classList.add('hidden');}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'||e.key==='/'&&!edit){e.preventDefault();showView('search');$('searchQuery').focus();}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='f'&&state.currentView==='reader'){e.preventDefault();$('pdfFind').focus();$('pdfFind').select();}if(!edit&&!dialog.open&&state.currentView==='reader'&&state.reader.pdf){if(e.key==='ArrowRight'){e.preventDefault();goPdfPage(state.reader.currentPage+1);}if(e.key==='ArrowLeft'){e.preventDefault();goPdfPage(state.reader.currentPage-1);}}});
function renderHistory(){const h=loadJSON('openscite_history_v25',[]);$('searchHistory').innerHTML=h.slice(0,5).map((q,i)=>`<button class="history-chip" data-history="${i}" title="${esc(q)}">${esc(q)}</button>`).join('');}
renderHistory();$('searchHistory').onclick=e=>{const b=e.target.closest('[data-history]');if(b){$('searchQuery').value=loadJSON('openscite_history_v25',[])[Number(b.dataset.history)]||'';runSearch(true);}};
document.addEventListener('research:search',()=>{const q=state.search.query;saveJSON('openscite_history_v25',[q,...loadJSON('openscite_history_v25',[]).filter(x=>x!==q)].slice(0,15));renderHistory();decorateSearch();});
for(const id of ['yearFrom','yearTo','searchOA','perPage'])$(id).addEventListener('change',()=>{if(state.search.query)runSearch(true);});
const comparison=new Map();
function workKey(w){return w.doi||w.id||w.title;}
function decorateSearch(){const works=sortedSearchWorks();$$('.paper-card',$('searchResults')).forEach((card,i)=>{const w=works[i];if(!w||card.querySelector('[data-compare]'))return;const key=workKey(w);card.querySelector('.paper-actions').insertAdjacentHTML('beforeend',`<button class="btn small" data-compare="${state.search.works.indexOf(w)}" aria-pressed="${comparison.has(key)}">${comparison.has(key)?'✓ 已選取':'＋ 比較'}</button><button class="btn small" data-cite="${state.search.works.indexOf(w)}">引用格式</button>`);});}
$('searchResults').addEventListener('click',e=>{let b=e.target.closest('[data-compare]');if(b){const w=state.search.works[Number(b.dataset.compare)],k=workKey(w);if(comparison.has(k))comparison.delete(k);else{if(comparison.size===3){toast('一次最多比較三篇論文');return;}comparison.set(k,w);}b.textContent=comparison.has(k)?'✓ 已選取':'＋ 比較';b.setAttribute('aria-pressed',comparison.has(k));$('compareTray').classList.toggle('hidden',!comparison.size);$('compareCount').textContent=`已選取 ${comparison.size} / 3 篇`;}b=e.target.closest('[data-cite]');if(b){const w=state.search.works[Number(b.dataset.cite)];showDialog('引用資訊',`<p>請以原文核對作者、年份與期刊資訊。作者名單可能為來源節錄。</p><label>文字引用<textarea class="control citation-copy" rows="4" readonly>${esc(`${w.authors} (${w.year||'n.d.'}). ${w.title}. ${w.source}. ${w.doi?'https://doi.org/'+w.doi:''}`)}</textarea></label><label>BibTeX<textarea class="control citation-copy" rows="8" readonly>${esc(bibtex(w))}</textarea></label>`);}});
$('compareClear').onclick=()=>{comparison.clear();$('compareTray').classList.add('hidden');renderSearch();decorateSearch();};
$('compareOpen').onclick=()=>{const ws=[...comparison.values()];showDialog('論文比較',`<div class="comparison-scroll"><table class="comparison-table"><thead><tr><th>項目</th>${ws.map(w=>`<th>${esc(w.title)}</th>`).join('')}</tr></thead><tbody>${[['作者','authors'],['年份','year'],['期刊 / 出處','source'],['引用次數','citations'],['摘要（來源原文）','abstract'],['DOI','doi']].map(([label,key])=>`<tr><th>${label}</th>${ws.map(w=>`<td>${esc(w[key]??'未提供')}</td>`).join('')}</tr>`).join('')}</tbody></table></div><p>比較依據為搜尋來源資料，未進行全文方法或結論比較。</p>`);};
function bibtex(w){const clean=s=>String(s||'').replace(/\\/g,'\\textbackslash{}').replace(/[{}]/g,'').replace(/[%&#_$]/g,'\\$&');return `@article{${clean((w.doi||w.id||'paper').replace(/[^a-z0-9]/gi,''))},\n  title = {${clean(w.title)}},\n  author = {${clean(w.authors).replace(/, /g,' and ')}},\n  year = {${clean(w.year)}},\n  journal = {${clean(w.source)}},\n  doi = {${clean(w.doi)}}\n}`;}
$('exportSearch').onclick=()=>{if(!state.search.works.length){toast('請先搜尋論文');return;}downloadText('openscite-search.bib',state.search.works.map(bibtex).join('\n\n'),'application/x-bibtex');};

let navMode='outline',outline=[],matches=[],matchIndex=-1;
const BOOKMARKS='openscite_bookmarks_v25',POSITIONS='openscite_positions_v25';
function renderDocumentNav(){const nav=$('documentNav');if(navMode==='outline'){nav.innerHTML=outline.length?outline.map((x,i)=>`<button class="document-link" data-outline="${i}" style="padding-left:${10+Math.min(x.depth,4)*12}px">${esc(x.title)}</button>`).join(''):'<p class="muted">這份 PDF 未提供目錄。可使用頁碼或全文搜尋導覽。</p>';}else if(navMode==='bookmarks'){const all=loadJSON(BOOKMARKS,[]).filter(x=>x.key===readerKey());nav.innerHTML=all.length?all.map(x=>`<div class="bookmark-row"><button class="document-link" data-page-link="${x.page}">第 ${x.page} 頁 · ${esc(x.label)}</button><button class="btn small" data-delete-bookmark="${x.page}" aria-label="刪除書籤">×</button></div>`).join(''):'<p class="muted">按「☆ 書籤」保存目前頁面。</p>';}else{nav.innerHTML=matches.length?matches.slice(0,200).map((m,i)=>`<button class="document-link ${i===matchIndex?'selected':''}" data-match="${i}"><b>第 ${m.page} 頁</b><span>${highlightHtml(m.snippet,$('pdfFind').value)}</span></button>`).join(''):'<p class="muted">輸入文字搜尋整份文件。</p>';}}
$$('[data-doc-nav]').forEach(b=>b.onclick=()=>{navMode=b.dataset.docNav;renderDocumentNav();});
$('documentNav').onclick=async e=>{const outlineButton=e.target.closest('[data-outline]');if(outlineButton){const item=outline[Number(outlineButton.dataset.outline)];try{let dest=typeof item.dest==='string'?await state.reader.pdf.getDestination(item.dest):item.dest;if(dest){const page=typeof dest[0]==='number'?dest[0]+1:await state.reader.pdf.getPageIndex(dest[0])+1;goPdfPage(page);}}catch{toast('目錄目的地無法解析');}}const page=e.target.closest('[data-page-link]');if(page)goPdfPage(Number(page.dataset.pageLink));const match=e.target.closest('[data-match]');if(match)selectMatch(Number(match.dataset.match));const remove=e.target.closest('[data-delete-bookmark]');if(remove){saveJSON(BOOKMARKS,loadJSON(BOOKMARKS,[]).filter(x=>!(x.key===readerKey()&&x.page===Number(remove.dataset.deleteBookmark))));renderDocumentNav();}};
async function documentReady(){const token=state.reader.renderToken;matches=[];matchIndex=-1;$('pdfFind').value='';$('findCount').textContent='';outline=[];try{const raw=await state.reader.pdf.getOutline();if(token!==state.reader.renderToken)return;function walk(items,depth=0){for(const x of items||[]){outline.push({title:x.title,dest:x.dest,depth});walk(x.items,depth+1);}}walk(raw);}catch{}if(token!==state.reader.renderToken)return;renderDocumentNav();const saved=loadJSON(POSITIONS,{})[readerKey()];if(saved?.page)goPdfPage(saved.page);$('readerProgress').textContent=state.reader.fullText.trim().length<30?'這份文件沒有可搜尋文字層（可能是掃描檔）；仍可閱讀和分析圖像。':`全文索引完成 · ${state.reader.pages} 頁 · ${state.reader.fullText.length.toLocaleString()} 字元`;if(state.reader.indexErrors?.length){$('readerProgress').textContent=`部分索引完成 · ${state.reader.pages-state.reader.indexErrors.length} / ${state.reader.pages} 頁；`+state.reader.indexErrors.map(x=>`第 ${x.page} 頁：${x.message}`).join('；');}}
document.addEventListener('research:document',documentReady);
function searchDocument(){const query=$('pdfFind').value.trim().toLowerCase();matches=[];matchIndex=-1;if(query){state.reader.pageTexts.forEach((text,i)=>{const lower=text.toLowerCase();let from=0,at;while((at=lower.indexOf(query,from))!==-1&&matches.length<1000){matches.push({page:i+1,start:at,snippet:text.slice(Math.max(0,at-45),at+query.length+95)});from=at+query.length;}});}$('findCount').textContent=query?`${matches.length}${matches.length===1000?'+':''} 筆`:'';navMode='matches';renderDocumentNav();markSearch();if(matches.length)selectMatch(0);}
$('pdfFind').addEventListener('input',debounce(searchDocument,180));$('pdfFind').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();selectMatch(matchIndex+(e.shiftKey?-1:1));}});
function selectMatch(i){if(!matches.length)return;matchIndex=(i+matches.length)%matches.length;goPdfPage(matches[matchIndex].page);$('findCount').textContent=`${matchIndex+1} / ${matches.length}`;renderDocumentNav();markSearch();}
$('findPrev').onclick=()=>selectMatch(matchIndex-1);$('findNext').onclick=()=>selectMatch(matchIndex+1);
function markSearch(){
 const q=$('pdfFind').value.trim().toLowerCase();
 for(const wrap of $$('.pdf-page',$('pdfPages'))){wrap.querySelector('.find-highlight-layer')?.remove();if(!q)continue;const overlay=document.createElement('div');overlay.className='find-highlight-layer';const bounds=wrap.getBoundingClientRect();
 for(const span of $$('.textLayer span',wrap)){const node=span.firstChild;if(!node||node.nodeType!==Node.TEXT_NODE)continue;const text=node.textContent.toLowerCase();let at=0,found;while((found=text.indexOf(q,at))>=0){const range=document.createRange();range.setStart(node,found);range.setEnd(node,found+q.length);for(const r of range.getClientRects()){const mark=document.createElement('span');mark.className='find-hit';Object.assign(mark.style,{left:`${(r.left-bounds.left)/bounds.width*100}%`,top:`${(r.top-bounds.top)/bounds.height*100}%`,width:`${r.width/bounds.width*100}%`,height:`${r.height/bounds.height*100}%`});overlay.appendChild(mark);}at=found+q.length;}}
 wrap.appendChild(overlay);}
}
document.addEventListener('research:page',markSearch);
$('bookmarkPage').onclick=()=>{if(!state.reader.pdf){toast('請先開啟 PDF');return;}const page=state.reader.currentPage,key=readerKey(),all=loadJSON(BOOKMARKS,[]);if(all.some(x=>x.key===key&&x.page===page)){toast('此頁已加入書籤');return;}const label=prompt('書籤名稱',`第 ${page} 頁`);if(label===null)return;all.push({key,page,label:label.slice(0,160)});saveJSON(BOOKMARKS,all);navMode='bookmarks';renderDocumentNav();toast('書籤已儲存');};
$('pdfViewport').addEventListener('scroll',debounce(()=>{if(!state.reader.pdf)return;const all=loadJSON(POSITIONS,{});all[readerKey()]={page:state.reader.currentPage,at:Date.now()};saveJSON(POSITIONS,all);},400),{passive:true});
$('focusReader').onclick=()=>{document.body.classList.toggle('reader-focus');$('focusReader').textContent=document.body.classList.contains('reader-focus')?'離開專注':'專注閱讀';};
$('downloadPdf').onclick=()=>{if(!state.reader.buffer){toast('請先開啟 PDF');return;}const url=URL.createObjectURL(new Blob([state.reader.buffer],{type:'application/pdf'})),a=document.createElement('a');a.href=url;a.download=safeFile((state.reader.fileName||state.reader.meta?.title||'paper').replace(/\.pdf$/i,''))+'.pdf';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
// Answers keep visible, clickable page references, while preserving escaped output.
const baseSetAssistant=setAssistant;setAssistant=function(title,body){baseSetAssistant(title,body);$('assistantOutput').innerHTML=$('assistantOutput').innerHTML.replace(/\[Page (\d+)\]/g,(m,n)=>Number(n)<=state.reader.pages?`<button class="page-citation" data-page-link="${n}">第 ${n} 頁 ↗</button>`:m);};
$('assistantOutput').addEventListener('click',e=>{const b=e.target.closest('[data-page-link]');if(b)goPdfPage(Number(b.dataset.pageLink));});

function decorateLibrary(){const q=$('libraryQuery').value.trim().toLowerCase(),tags=loadJSON('openscite_tags_v25',{});const cards=$$('.library-card',$('libraryList'));cards.forEach((card,i)=>{const w=state.library[i];if(!w)return;card.dataset.libraryIndex=i;const label=tags[w.key]||'';card.hidden=![w.title,w.authors,w.source,label].join(' ').toLowerCase().includes(q);if(!card.querySelector('[data-tags]'))card.insertAdjacentHTML('beforeend',`<div class="tag-row"><button class="btn small ghost" data-tags="${i}" ${label?'':'data-ui-tag'}>${esc(label||'＋ 加入標籤')}</button></div>`);});const mode=$('libraryOrder').value;cards.sort((a,b)=>{const x=state.library[Number(a.dataset.libraryIndex)],y=state.library[Number(b.dataset.libraryIndex)];return mode==='title'?x.title.localeCompare(y.title):mode==='year'?Number(y.year||0)-Number(x.year||0):String(y.added).localeCompare(String(x.added));});cards.forEach(c=>$('libraryList').appendChild(c));$('libraryCount').textContent=`${cards.filter(c=>!c.hidden).length} / ${state.library.length} 篇`;}
const baseRenderLibrary=renderLibrary;renderLibrary=function(){baseRenderLibrary();decorateLibrary();};
$('libraryQuery').oninput=debounce(()=>renderLibrary(),150);$('libraryOrder').onchange=()=>renderLibrary();
$('libraryList').addEventListener('click',e=>{const b=e.target.closest('[data-tags]');if(!b)return;const w=state.library[Number(b.dataset.tags)],tags=loadJSON('openscite_tags_v25',{});const label=prompt('標籤（以逗號分隔）',tags[w.key]||'');if(label!==null){tags[w.key]=label.slice(0,250);saveJSON('openscite_tags_v25',tags);renderLibrary();}});
const backupKeys=[STORE.library,STORE.notes,STORE.highlights,BOOKMARKS,POSITIONS,'openscite_tags_v25','openscite_chat_v1'];
$('backupWorkspace').onclick=()=>{const data=Object.fromEntries(backupKeys.map(k=>[k,loadJSON(k,k===POSITIONS||k==='openscite_tags_v25'||k==='openscite_chat_v1'?{}:[])]));downloadText('openscite-workspace-'+new Date().toISOString().slice(0,10)+'.json',JSON.stringify({format:'openscite-workspace',version:1,exportedAt:new Date().toISOString(),includesPdfFiles:false,data},null,2),'application/json');};
$('restoreWorkspace').onclick=()=>$('backupFile').click();
function validateBackup(d){if(d?.format!=='openscite-workspace'||d.version!==1||!d.data||typeof d.data!=='object')throw new Error('不是支援的 OpenScite 備份格式');for(const key of backupKeys){const value=d.data[key];if(value===undefined)continue;const objectKey=key===POSITIONS||key==='openscite_tags_v25'||key==='openscite_chat_v1';if(objectKey?(typeof value!=='object'||!value||Array.isArray(value)):!Array.isArray(value))throw new Error('備份資料結構錯誤');if(!objectKey)for(const row of value){if(!row||typeof row!=='object')throw new Error('備份項目格式錯誤');if(key===STORE.library&&(typeof row.key!=='string'||typeof row.title!=='string'))throw new Error('缺少論文標題或識別碼');if((key===STORE.notes||key===STORE.highlights)&&typeof row.paperKey!=='string')throw new Error('筆記缺少論文識別碼');}}return d.data;}
$('backupFile').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>20000000)throw new Error('備份超過 20 MB 限制');const data=validateBackup(JSON.parse(await f.text()));if(!confirm('將備份與現有資料合併？相同項目保留目前版本，PDF 原檔需另行匯入。'))return;const staged={};for(const key of backupKeys){if(data[key]===undefined)continue;const current=loadJSON(key,Array.isArray(data[key])?[]:{});if(Array.isArray(data[key])){const identity=x=>key===STORE.library?x.key:key===BOOKMARKS?`${x.key}:${x.page}`:`${x.paperKey}:${x.id||x.text||x.quote}:${x.created}`;const rows=new Map(data[key].map(x=>[identity(x),x]));current.forEach(x=>rows.set(identity(x),x));staged[key]=[...rows.values()];}else staged[key]={...data[key],...current};}const before=Object.fromEntries(Object.keys(staged).map(k=>[k,localStorage.getItem(k)]));try{for(const [k,v]of Object.entries(staged))localStorage.setItem(k,JSON.stringify(v));}catch(err){for(const [k,v]of Object.entries(before))if(v===null)localStorage.removeItem(k);else localStorage.setItem(k,v);throw new Error('儲存空間不足，已復原匯入前資料');}renderLibrary();toast('備份已合併；PDF 原檔請另行保留。');}catch(err){toast(`匯入失敗：${err.message}`,6000);}finally{e.target.value='';}};
// Persistent, removable notes: target the saved item rather than its list position.
const baseRenderNotes=renderNotes;renderNotes=function(){baseRenderNotes();const list=[...state.reader.notes].reverse();$$('.note-card',$('notesList')).forEach((c,i)=>c.insertAdjacentHTML('beforeend',`<div class="mini-actions">${list[i].page?`<button class="btn small" data-note-page="${list[i].page}">回到第 ${list[i].page} 頁</button>`:''}<button class="btn small" data-note-delete="${list[i].id}">刪除筆記</button></div>`));};
$('notesList').onclick=e=>{const page=e.target.closest('[data-note-page]');if(page)goPdfPage(Number(page.dataset.notePage));const del=e.target.closest('[data-note-delete]');if(del&&confirm('刪除這則筆記？')){const all=loadJSON(STORE.notes,[]).filter(n=>!(n.paperKey===readerKey()&&String(n.id)===del.dataset.noteDelete));saveJSON(STORE.notes,all);state.reader.notes=all.filter(n=>n.paperKey===readerKey());renderNotes();}};
// Give icon-only controls explicit accessible names.
for(const [id,label]of Object.entries({zoomIn:'放大',zoomOut:'縮小',prevPdfPage:'上一頁',nextPdfPage:'下一頁',pageJump:'跳至頁碼',searchQuery:'搜尋論文',closeModal:'關閉 AI 設定'}))$(id).setAttribute('aria-label',label);
$('aiModal').setAttribute('aria-label','AI 設定');

const notesWithActions=renderNotes;renderNotes=function(){notesWithActions();const items=state.reader.highlights||[];if(items.length)$('notesList').insertAdjacentHTML('beforeend',`<h4>高亮標註 · ${items.length}</h4>`+items.map((h,i)=>`<div class="note-card"><q>${esc(h.text)}</q><div class="mini-actions">${h.page?`<button class="btn small" data-note-page="${h.page}">第 ${h.page} 頁</button>`:''}<button class="btn small" data-highlight-delete="${i}">移除高亮</button></div></div>`).join(''));};
$('notesList').addEventListener('click',e=>{const b=e.target.closest('[data-highlight-delete]');if(!b)return;const h=state.reader.highlights[Number(b.dataset.highlightDelete)];if(!h)return;const all=loadJSON(STORE.highlights,[]).filter(x=>!(x.paperKey===h.paperKey&&x.created===h.created&&x.text===h.text));if(saveJSON(STORE.highlights,all)){state.reader.highlights=all.filter(x=>x.paperKey===readerKey());$$('.textLayer',$('pdfPages')).forEach(applyTextMarks);$$('.pdf-page',$('pdfPages')).forEach(w=>renderSavedHighlights(w,Number(w.dataset.page)));renderNotes();}});
