const {test}=require('node:test');const assert=require('node:assert/strict');const {EventEmitter}=require('node:events');const {PassThrough}=require('node:stream');const {Rpc}=require('./rpc.cjs');const {Assistant}=require('./assistant.cjs');
class Fake extends EventEmitter{constructor(){super();this.calls=[];}async request(method,p){this.calls.push({method,p});if(method==='account/read')return {account:{type:'chatgpt'}};if(method==='model/list')return {data:[{model:'available',supportedReasoningEfforts:[{reasoningEffort:'medium'}],defaultReasoningEffort:'medium',inputModalities:['text','image']}],nextCursor:null};if(method==='thread/start')return {thread:{id:'thread'}};if(method==='turn/start'){queueMicrotask(()=>{this.emit('notification',{method:'item/completed',params:{threadId:'thread',item:{type:'agentMessage',id:'message',text:'依據 [Page 3] 的回答'}}});this.emit('notification',{method:'turn/completed',params:{threadId:'thread',turn:{status:'completed'}}});});return {turn:{id:'turn'}};}return {};}}
const body={desktopModel:'available',desktopEffort:'medium',input:[{role:'system',content:[{type:'input_text',text:'Explain evidence'}]},{role:'user',content:[{type:'input_text',text:'[Page 3] Paper text'}]}]};
test('routes selected model, evidence, schema and final event even before turn response',async()=>{const rpc=new Fake(),a=new Assistant(rpc,'/empty');const out=await a.ask({...body,text:{format:{schema:{type:'object'}}}});assert.match(out,/Page 3/);const turn=rpc.calls.find(c=>c.method==='turn/start').p;assert.equal(turn.model,'available');assert.equal(turn.effort,'medium');assert.deepEqual(turn.outputSchema,{type:'object'});assert.equal(turn.sandboxPolicy.type,'readOnly');assert.equal(a.active,null);assert.equal(rpc.listenerCount('notification'),0);});
test('requires account and rejects unavailable models',async()=>{const a=new Assistant(new Fake(),'/empty');await assert.rejects(a.ask({...body,desktopModel:'invented'}),/可用/);a.rpc.request=async()=>({account:null});await assert.rejects(a.ask(body),/登入/);});
test('cancel before thread startup never sends turn',async()=>{const rpc=new Fake(),original=rpc.request.bind(rpc);let release;rpc.request=(m,p)=>m==='thread/start'?new Promise(r=>release=r):original(m,p);const a=new Assistant(rpc,'/empty'),pending=a.ask(body);await new Promise(r=>setImmediate(r));await a.cancel();release({thread:{id:'thread'}});await assert.rejects(pending,/取消/);assert.ok(!rpc.calls.some(c=>c.method==='turn/start'));});
test('rejects simultaneous requests',async()=>{const rpc=new Fake();rpc.request=()=>new Promise(()=>{});const a=new Assistant(rpc,'/empty');a.ask(body);await assert.rejects(a.ask(body),/正在進行/);});
test('JSON RPC handles split lines, server requests and disconnect',async()=>{const child=new EventEmitter();child.stdout=new PassThrough();child.stderr=new PassThrough();child.stdin=new PassThrough();child.kill=()=>{};const rpc=new Rpc(child);const pending=rpc.request('account/read');child.stdout.write('{"id":1,"res');child.stdout.write('ult":{"account":null}}\n');assert.deepEqual(await pending,{account:null});const failure=rpc.request('test');child.emit('exit');await assert.rejects(failure,/連線已結束/);assert.equal(rpc.pending.size,0);});
test('cancel an active turn interrupts exact job and cleans listeners',async()=>{const rpc=new Fake(),original=rpc.request.bind(rpc);rpc.request=(m,p)=>{if(m==='turn/start'){rpc.calls.push({method:m,p});return Promise.resolve({turn:{id:'running'}});}return original(m,p);};const a=new Assistant(rpc,'/empty');const pending=a.ask(body);await new Promise(r=>setImmediate(r));await a.cancel();await assert.rejects(pending,/取消/);assert.deepEqual(rpc.calls.find(c=>c.method==='turn/interrupt').p,{threadId:'thread',turnId:'running'});assert.equal(rpc.listenerCount('notification'),0);});
test('vision rejects external URLs and preserves local data images',async()=>{const rpc=new Fake(),a=new Assistant(rpc,'/empty');const imageBody=JSON.parse(JSON.stringify(body));imageBody.input[1].content.push({type:'input_image',image_url:'https://external.test/image.png'});await assert.rejects(a.ask(imageBody),/本機/);imageBody.input[1].content[1].image_url='data:image/png;base64,aGVsbG8=';await a.ask(imageBody);assert.equal(rpc.calls.find(c=>c.method==='turn/start').p.input[1].type,'image');});
